import { createSlice } from "@reduxjs/toolkit";

// The CATEGORIES_INITIAL_STATE object defines the initial state of the categories slice, which is simply an empty array.
export const CATEGORIES_INITIAL_STATE ={
    categories: [],
};

// The categoriesSlice object defines the slice itself, including its name, initial state, and a set of reducers. 
//The setCategories reducer takes the current state and an action as its input, and sets the categories property of the state to the payload of the action.
export const categoriesSlice = createSlice({
    name: 'categories',
    initialState:CATEGORIES_INITIAL_STATE,
    reducers:{
        setCategories(state, action){
            state.categories = action.payload;
        },
    },
});
// The setCategories action is a named export that allows other parts of the application to dispatch the setCategories action to update the state.
export const {setCategories} = categoriesSlice.actions;

// The categoriesReducer is also a named export that provides a reducer function for the categories slice.
// This reducer is automatically generated by the createSlice() function from the slice definition above.
export const categoriesReducer = categoriesSlice.reducer;

//Overall, this code provides a simple and structured way to manage a list of categories in a Redux store. The categoriesSlice object defines the shape of the slice, including its initial state and a set of reducers. 
//The setCategories action can be dispatched to update the state, and the categoriesReducer provides a reducer function to handle those updates.